export {LandingPage} from './Home'
export {SignUp, SignIn, ForgotPassword, ResetPassword} from './Auth'
export {Packages, PackageDetails} from './Packages'
export {default as Contact} from './Contact/Contact'
export {Bookings,CreatePackage,UpdatePackage,TourPackages,AddReferal,UpdateReferal,Users} from './Admin'
export {default as About} from './About/About'
export {default as Destinations} from './Destinations/Destinations'
