export {LandingPage} from './Home'
export {SignUp, SignIn, ForgotPassword, ResetPassword} from './Auth'
export {Packages, PackageDetails} from './Packages'
export {default as Contact} from './Contact/Contact'
export {Dashboard,Bookings,CreatePackage,UpdatePackage,TourPackages,AddReferal,UpdateReferal} from './Admin'
export {default as About} from './About/About'
export {default as Destinations} from './Destinations/Destinations'
export {default as Category} from './Destinations/Category'
export {default as Classes} from './Classes/Classes'
export {default as Gallery} from './Gallery/Gallery'
