export {default as Bookings} from './Bookings'
export {default as CreatePackage} from './Create'
export {default as UpdatePackage} from './Update'
export {default as TourPackages} from './Packages'
export {default as Users} from './Users'
export {default as AddReferal} from './AddRef'
export {default as UpdateReferal} from './UpdateRef'